name: Compile Solidity Contracts

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Que se duerma el proceso
        run: sleep 4

      - name: A que hora ha terminado el despliegue chicos / as
        run: date

      - name: Quiero ver si mi página funciona
        run: curl -k "https://as.com"

      - name: Y ahora quiero saber con que version de git estoy trabajando
        run: git version

      - name: Y despedida de clase
        run: echo "que tengais buen finde, que os regalen muchas cosas, que sois muy buena gente"

    - name: Compile contracts
      run: Compilemos
        npx solcjs --bin --abi --include-path node_modules/ --base-path . -o build contracts/HolaMundo.sol
        

